# User Input Template
# 2019 - romuald@redhat.com
#
# If multiple objects need to be created, use the pattern [object1,object2,object3,...]  
# Example: [vs04_cap1_st5400_o01,vs04_cap1_st5400_o02,vs04_cap1_st5400_o03]
#

#-------------------------------------------------------------------------------------------#
# Modify to your needs
#-------------------------------------------------------------------------------------------#
# site
site: cap                                           # { cap, perex } 

## volume info
volname: vs0[1,2]_[cap1,perex2]_prod_cifs_xx        # volname = name of the volume(s)
qtreesize: 1                                        # size of the qtree if no qtree is given 
qtreename: qtrw                                      # if no qtree put ""
sharename: monshare$                                # smb share name

## storage disk class {sata, sas, ssd}
disktype: sata                                      # {sata=bronze, sas=silver, ssd=gold} 
#-------------------------------------------------------------------------------------------#


#-------------------------------------------------------------------------------------------#
# don't change/modify
provtype: nas
volsize: "{{ (qtreesize*1.2)|int}}"                 # volize  = volume size in gb
juncpath: "{{ volname }}"                           # 
maxpercentused: 85
#-------------------------------------------------------------------------------------------#










