# User Input Template
# 2019 - romuald@redhat.com
#
# If multiple objects need to be created, use the pattern [object1,object2,object3,...]  
# Example: [vs04_cap1_st5400_o01,vs04_cap1_st5400_o02,vs04_cap1_st5400_o03]
#

#-------------------------------------------------------------------------------------------#
# Modify to your needs
#-------------------------------------------------------------------------------------------#
# site
site: cap                                           # { cap, perex } 

## volume info
volname: vs0[1,2]_[cap1,perex2]_prod_nfs_xx         # volname = name of the volume(s)
qtreesize: 1                                        # lunsize = size(s) of the requested LUN 
qtreename: qtrw
exportclient: [157.164.70.11,157.164.70.10]         # igroups = host ports allowed access

## storage disk class {sata, sas, ssd}
disktype: sata                                      # {sata=bronze, sas=silver, ssd=gold} 
#-------------------------------------------------------------------------------------------#


#-------------------------------------------------------------------------------------------#
# don't change/modify
provtype: san
volsize: "{{ (qtreesize*1.2)|int}}"                   # volize  = volume size in gb
juncpath: "/{{ volname }}"                            # 
maxpercentused: 85
#-------------------------------------------------------------------------------------------#










