# User Input Template
# 2019 - romuald@redhat.com
#
# If multiple objects need to be created, use the pattern [object1,object2,object3,...]  
# Example: [vs04_cap1_st5400_o01,vs04_cap1_st5400_o02,vs04_cap1_st5400_o03]
#

#-------------------------------------------------------------------------------------------#
# Modify to your needs
#-------------------------------------------------------------------------------------------#
# site
site: cap                                           # { cap, perex } 

## volume info
volname: vs03_cap1_esx6_gold_xx                     # volname = name of the volume(s)
lunsize: 4096                                       # lunsize = size(s) of the requested LUN 
ostype: vmware                                      # {linux, vmware, windows}

## igroups
igroups: vs03_ig_esx6_fcp                           # igroups = host ports allowed access

## storage disk class {sata, sas, ssd}
disktype: sata                                      # {sata=bronze, sas=silver, ssd=gold} 
#-------------------------------------------------------------------------------------------#


#-------------------------------------------------------------------------------------------#
# don't change/modify
provtype: san
volsize: "{{ (lunsize*1.2)|int}}"                   # volize  = volume size in gb
lunname: "{{ volname }}.lun"                        # lunname = volname + .lun as a standard
maxpercentused: 85
#-------------------------------------------------------------------------------------------#

