# site
site: cap				# { cap, perex } 

## volume info
volname: moncu 				# volname = name of the volume
lunsize: 1                              # lunsize = size of the requested LUN 
ostype: vmware 				# {windows, linux, vmware}

## igroups
igroups: [vs03_ig_esx6_fcp,vs03_ig_commvault_fcp] 	# for datastore with commvault access
#igroups: vs03_ig_esx6_fcp				# for datastore with commvault access

## storage disk class {sata, sas, ssd}
disktype: sata				# {sas, sata, ssd} 


# don't change/modify
provtype: san
volsize: "{{ (lunsize*1.2)|int}}"       # volize  = volume size in gb
lunname: "{{ volname }}.lun"            # name of the lun is generally the volume + .lun
maxpercentused: 80

