- hosts: localhost 
  gather_facts: false
  connection: local

  tasks:
  - include_vars:
      dir: tasks/inputs
      files_matching: "{{ input }}.yml"
  - include_vars:
      dir: tasks/vars
      files_matching: "{{ site }}.yml"

  - name: Gathering aggregate vfiler volume info
    include_tasks: tasks/ntap_facts.yml

  # create volume 
  - name: Create volume 
    include_tasks: tasks/ntap_vol.yml 
    vars: 
      - vserver == "{{ vlun }}"
    when: provtype == 'san' and ostype == 'vmware' 

#  # if SAN 
#  - name: Create LUN(s)
#    include_tasks: tasks/ntap_lun.yml
#    when: 
#      - provtype == 'san'
#
#  - name: Map LUN(s)
#    include_tasks: tasks/ntap_lunmap.yml
#    when: 
#      - provtype == 'san'
#
#  # if NAS
#  - name: Create qtree
#    include_tasks: tasks/ntap_qtree.yml
#    when: 
#      - qtreename  != ''
#
#  - name: Create smb share
#    include_tasks: tasks/ntap_smb.yml
#    when: 
#      - provtype  == 'nas'
#      - prototype == 'smb'
#
#  - name: Create nfs share
#    include_tasks: tasks/ntap_smb.yml
#    when: 
#      - provtype  == 'nas'
#      - prototype == 'nfs'
#
#